package br.com.sistemaEstacionamento.view;

import br.com.sistemaEstacionamento.control.UsuarioControl;
import javax.swing.JOptionPane;
/**
 *
 * @author Daniel
 */
public class LoginView extends javax.swing.JInternalFrame {

    private UsuarioControl usuarioControl;
        
    public LoginView() {
        initComponents();
        setSize(500, 304);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnOk = new javax.swing.JButton();
        lblImagemFundo = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Estacionamento");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(null);

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login:");
        getContentPane().add(lblLogin);
        lblLogin.setBounds(140, 240, 60, 20);

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(140, 260, 70, 20);

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(210, 240, 90, 20);

        txtSenha.setToolTipText("");
        getContentPane().add(txtSenha);
        txtSenha.setBounds(210, 260, 90, 20);

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(310, 240, 60, 40);

        lblImagemFundo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sistemaEstacionamento/view/bakcground.jpg"))); // NOI18N
        lblImagemFundo.setText("Senha");
        getContentPane().add(lblImagemFundo);
        lblImagemFundo.setBounds(0, 0, 561, 304);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (usuarioControl.realizarLogin()){
            MenuView menuView = new MenuView();
            this.desktopPane.add(menuView);
            menuView.setVisible(true);
        }
        else 
        {
            txtSenha.setText("");
            JOptionPane.showMessageDialog(this, true, "Usuário ou senha inválido(s)!", JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_btnOkActionPerformed

   
    private javax.swing.JDesktopPane desktopPane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblImagemFundo;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
